#Loops for installing packages one by one
---

- name: Install software packages
  hosts: Qaserver
  become: true
  tasks:
   - name: Install software
     yum:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - git
      - java-1.8.0-openjdk-devel.x86_64
      - maven

...
