---
- name: configuring apache2
  hosts: all
  become: true
  tasks:
   - name: Install httpd
     yum:
      name: httpd
      state: present
   - name: Edit index.html file
     copy:
      content: "Welcome to Playbooks\n"
      dest: /var/www/html/index.html
   - name: Restart httpd
     service:
      name: httpd
      state: restarted
...
